#deprecated

all: Atomo.java CStamp.java Gerador.java
	javac Pair.java
	javac BitArray.java
	javac Id.java
	javac Event.java
	javac Atomo.java
	javac Gerador.java
	javac Dice.java
	javac Bag.java
	javac Stamp.java
	javac CStamp.java
	javac main.java

clean:
	rm *.class
	